name: tototales
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.1.0
  http: ^1.2.1
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.8.1
  connectivity_plus: ^5.0.2
  device_preview: ^1.1.0

  # Firebase & Google sign-in (Web-ready)
  firebase_core: ^2.30.0
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  google_sign_in: ^6.1.6
  js: ^0.6.7
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/backgrounds/
    - assets/icons/
