// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0aKTQ3UYmT477G6UkOsbfXWh8Afj0AFQ',
    appId: '1:257265126210:web:428122f458db20b0c156db',
    messagingSenderId: '257265126210',
    projectId: 'tototales-78b9a',
    authDomain: 'tototales-78b9a.firebaseapp.com',
    storageBucket: 'tototales-78b9a.appspot.com', // ✅ FIXED THIS LINE
    measurementId: 'G-SDX93GLDF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1AM9Y3Ji4joim0xDxbkF95d0iT_mP8JI',
    appId: '1:257265126210:android:b1a53da2ff897b3ac156db',
    messagingSenderId: '257265126210',
    projectId: 'tototales-78b9a',
    storageBucket: 'tototales-78b9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNV0A69D49bk1v3_mKF9Ta2qdtNBsk4Pg',
    appId: '1:257265126210:ios:92e513f8a183ebccc156db',
    messagingSenderId: '257265126210',
    projectId: 'tototales-78b9a',
    storageBucket: 'tototales-78b9a.firebasestorage.app',
    iosBundleId: 'com.example.totoTales',
  );

}